language: python
python:
  - "3.5"
install:
  - pip install pytest-cov
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - make test
  - py.test --doctest-modules -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls