language: python
python:
  - "3.5"
install:
  - pip install pytest pytest-cov pytest-pep8
  - pip install coveralls
script:
  #- make test
  #- py.test --doctest-modules -v --cov coveralls --cov-report term-missing
  - py.test test_rpn.py --doctest-modules --pep8 rpn.py -v --cov coveralls --cov-report term-missing
  #- coverage run --source=. -m unittest
after_success:
  - coveralls